storage: ./storage
auth:
  github-oauth-ui:
    org: GITHUB_OAUTH_ORG
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: npmjs
  '**':
    proxy: npmjs
    access: $all
    publish: $authenticated
logs:
  - {type: stdout, format: pretty, level: http}
middlewares:
  github-oauth-ui:
    client-id: GITHUB_OAUTH_CLIENT_ID
    client-secret: GITHUB_OAUTH_CLIENT_SECRET
store:
  aws-s3-storage:
    bucket: AWS_S3_BUCKET_NAME
    region: AWS_REGION
    accessKeyId: AWS_ACCESS_KEY_ID
    secretAccessKey: AWS_SECRET_ACCESS_KEY
